version: "3"
services:
  server:
    image: jetbrains/teamcity-server:2017.1
    ports:
      - "8111:${PORT:-8111}"
    volumes:
      - ${DATA_PATH:-~/development/teamcity/data/}:/data/teamcity_server/datadir
      - ${LOGS_PATH:-~/development/teamcity/logs/}:/opt/teamcity/logs
  agent:
    image: teamcity-docker-agent-android:0.1
    volumes:
      - ${CONF_PATH:-~/development/teamcity/agent/}:/data/teamcity_agent/conf
    environment:
      - SERVER_URL=${SERVER_URL}
